Makefile
a
b
builtins_cd_pwd.c
builtins_cd_pwd.o
builtins_echo.c
builtins_echo.o
builtins_env_export_utils.c
builtins_env_export_utils.o
builtins_env_unset_export.c
builtins_env_unset_export.o
builtins_exit.c
builtins_exit.o
builtins_export_utils.c
builtins_export_utils.o
builtins_unset_utils.c
builtins_unset_utils.o
c
command_init.c
command_init.o
command_parser.c
command_parser.o
command_path.c
command_path.o
command_redirection.c
command_redirection.o
docs
en.subject.pdf
env_expand_main.c
env_expand_main.o
env_expand_utils1.c
env_expand_utils1.o
env_expand_utils2.c
env_expand_utils2.o
executor_child.c
executor_child.o
executor_exec.c
executor_exec.o
executor_main.c
executor_main.o
executor_utils.c
executor_utils.o
get_next_line
heredoc.c
heredoc.o
libft
lst_functions.c
lst_functions.o
main.c
main.o
memory.c
memory.o
mermaid-diagram-2025-04-18-220539.svg
minishell
minishell.h
signals.c
signals.o
test_minishell2.sh
token_types.c
token_types.o
token_utils.c
token_utils.o
tokenizer.c
tokenizer.o
utils.c
utils.o
